"""add relations user url

Revision ID: a27c062289ee
Revises: a1d75982b5d2
Create Date: 2025-02-17 14:47:53.128088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27c062289ee'
down_revision: Union[str, None] = 'a1d75982b5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'url', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='foreignkey')
    op.drop_column('url', 'user_id')
    # ### end Alembic commands ###
